### ISSUE TITLE
param examples have no effect on UI

### ISSUE THREAD

**Issue by bourdakos1** [bee-travels/openapi-comment-parser#12]
If a param has an example, the UI should use the example as the placeholder for the text input and render an example in the params table.

Example:
```yaml
components:
  schemas:
    CurrencyCode:
      type: string
      example: USD
```
```js
/**
 * GET /currency/{code}
 * @pathParam {CurrencyCode} code - A three letter currency code.
 * @response 200 - OK
 */
```

should render:
| Path Params |
| --- |
| `code` string[] - REQUIRED<br/>A three letter currency code.<br/>Example: `USD` |

with a try it out example:
`code`
| USD |
| --- |
